### ISSUE TITLE
The abstract needs clarification

### ISSUE THREAD

**Issue by andrekorol** [reflexer-labs/whitepapers#1]
For the sake of clarity, I think something is missing on the line "...and issue a reflex bond that follows the price of its underlying ____ in a dampened way."

**Comment by stefanionescu** [comment]
[EDIT]: we can add "underlying collateral" if that works

**Comment by andrekorol** [comment]
> [EDIT]: we can add "underlying collateral" if that works

That's what I was implicitly getting out of the context, but I believe stating that explicitly would improve readability.  

On another note, congratulations on implementing such an interesting DeFi protocol for issuing reflex bonds on Ethereum! I can't wait to experiment with it and to see what the community builds on top of it :)

**Comment by stefanionescu** [comment]
It's fixed!

And thank you! It's not really implemented yet but I have some plans to launch a very dumb demo way sooner than expected and engage the community.
